### ISSUE TITLE
Gesture handler called with wrong template instance in list

### ISSUE THREAD

**Issue by quarterto** [chriswessels/meteor-hammer#15]
I'm rendering a collection as a list, and each list item is a template with gesture handlers. When the handler fires, the `template` is always the last item in the list, regardless of which item the gesture was fired on. I'm using Meteor 1.1.0.2 and meteor-hammer 3.1.1.

**Comment by chriswessels** [comment]
Hey @quarterto,

Thanks for the bug report. Please could you try version `4.0.0-rc1` of chriswessels:hammer, I suspect it may solve your problem.

The bad news is that the API has changed in the slated `4.0.0` release, but I believe the new API is far more robust and gives the developer more transparency and control. See the README here: https://github.com/chriswessels/meteor-hammer/blob/rewrite/README.md

Since `4.0.0` hasn't been released as stable on Atmosphere yet, you'll need to run the following command in your Meteor project folder to try it out:

    $ meteor add chriswessels:hammer@4.0.0-rc1

Please give it a try, and let me know if you have any questions about the new API or how to convert your existing implementation. I expect `4.0.0` to be released as stable very soon (and once it has been released, you'll get the stable next time you `meteor update`).

Kind regards,
Chris

**Comment by chriswessels** [comment]
Hey @quarterto,

`4.0.0` released on Atmosphere with new API.

Please see [README.md](https://github.com/chriswessels/meteor-hammer/blob/master/README.md) and [MIGRATION.md](https://github.com/chriswessels/meteor-hammer/blob/master/MIGRATION.md).

Chris
