### ISSUE TITLE
requireFailure for vertical/horizontal pan

### ISSUE THREAD

**Issue by skylerapp** [chriswessels/meteor-hammer#17]
Hi, 
First of all, thank you for the package, it works great.

I'm trying to implement a "cards" kind of interface like this example (https://cdn.rawgit.com/hammerjs/hammer.js/master/tests/manual/nested.html) and so far have got the horizontal pans working but I can't get the vertical pans to work. Somehow the requireFailure won't work for me and the vertical pans only work after a horizontal pan is triggered (I'm trying to have both directions work independently).

This is my config code:

    configureHammer: function () {
        return function (hammer, t) {
            var vertical = new Hammer.Pan({
                event: 'panv',
                direction: Hammer.DIRECTION_VERTICAL
            });
            var horizontal = new Hammer.Pan({
                event: 'panh',
                direction: Hammer.DIRECTION_HORIZONTAL
            });
            vertical.requireFailure(horizontal);

            hammer.add([vertical, horizontal]);

            return hammer;
        }
    },

And I have a hammertoucharea like so:

        {{#HammerTouchArea configureCallback=configureHammer gestureMap=templateGestures}}
        ...
        {{/HammerTouchArea}}

And my templateGestures are simply "panleft", "panright", "panup", and "pandown"

Would you have any suggestions? Am I doing something wrong?

Olivier

**Comment by chriswessels** [comment]
Hey @skylerapp,

I haven't tested this, but I suspect your events aren't working because you're listening for the wrong ones in `templateGestures`.

The events `panleft`, `panright`, `panup` and `pandown` are emitted by the default Pan recognizer associated with the `Hammer.Manager` instance (not the ones you've created and attached yourself). If you look here, http://hammerjs.github.io/recognizer-pan, the notes section says that this recognizer instance by default only listens for horizontal gestures.

Try changing your `templateGestures` gesture map to listen to events that are prefixed by `panv` or `panh` instead of just `pan`. So, `panvup` or `panvdown`. These are the events that should be emitted by the recognizers you've attached in `configureHammer`.

Hope this helps!

Kind regards,
Chris

**Comment by chriswessels** [comment]
@skylerapp, did you try the fix?

**Comment by skylerapp** [comment]
Hi Chris,

Thanks for the answer. I ended up switching to the original package and got it to work following their examples. But now that I am more comfortable with hammer.js, I can see why it wasn't working.

Thanks for your help anyways!
