### ISSUE TITLE
How to set Pan threshold

### ISSUE THREAD

**Issue by emenoh** [chriswessels/meteor-hammer#7]
I'm trying to work out how to update the Pan threshold setting. Does Template.template.hammerOptions() expose this? Can you provide an example of using this? If the per template options object can't set the threshold, is there a straightforward way to do so? Thanks!

**Comment by emenoh** [comment]
I've found a working method. Maybe include this in your documentation.

In the template.rendered callback you can use the Jquery data object to update the Hammer Manager instance on the element. 

e.g. $('#my-div').data('hammer').get('pan').set({ threshold: 50 });

You can verify the changed value by the logging the Jquery object $('#my-div').data() to the console. 

This is probably a known thing for users of the Jquery plugin but it's non-obvious when you add it to a Meteor project via a package.

**Comment by chriswessels** [comment]
Thanks @emenoh!

I've just released 3.0.0-rc1 which uses a single instance of Hammer.js attached to the body element rather than per-element instances. This was to work around Blaze replacing the elements without warning causing the Hammer instances being lost.

You can try the new version by running
`$ meteor add chriswessels:hammer@3.0.0-rc1`

You will need to use `$('body').data('hammer').set(options)` to set application-wide options for Hammer.js though.

Please let me know if it works for you.

Thanks,
Chris

**Comment by emenoh** [comment]
Sweet... that sounds great. I'll try it out.

On Wed, Mar 4, 2015 at 1:12 PM, Chris Wessels <notifications@github.com>
wrote:

> Closed #7 <https://github.com/chriswessels/meteor-hammer/issues/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chriswessels/meteor-hammer/issues/7#event-246238342>.
>



-- 
James Hatfield

jhat.home@gmail.com
http://www.linkedin.com/in/jameshatfield
http://www.medium.com/@emenoh
@emenoh

Dallas/Fort Worth Metro Area
